### ISSUE TITLE
Remote Class connect methods and disconnect methods

### ISSUE THREAD

**Issue by okcatman** [swtcpro/jingtum-lib-python#2]
访问底层与节点交互需要示例Remote类，然后手动连接和关闭连接。
remote = Remote()
remote.connect()
在几次连接后会出现BrokenPipeError: [Errno 32] Broken pipe
需要再次手动连接，而关闭连接时有时会websocket - ERROR - close status: 31522 错误

**Comment by wanpixiaozi** [comment]
Can you post your test port config and testcase, i have tried 10 times loop test, no issue found
